# Generated by Django 5.2 on 2025-04-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=200)),
                ('resposta', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='filme',
            name='descricao',
            field=models.TextField(max_length=1000),
        ),
    ]
