# Generated by Django 5.2 on 2025-04-22 01:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0002_pergunta_alter_filme_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='categoria',
            field=models.CharField(choices=[('ANIME', 'Anime'), ('AVENTURA', 'Aventura'), ('AÇÃO', 'Ação'), ('TERROR', 'Terror'), ('ROMANCE', 'Romance'), ('COMEDIA', 'Comedia'), ('DOCUMENTARIO', 'Documentário'), ('SUSPENSE', 'Suspense'), ('DRAMA', 'Drama'), ('INFATIL', 'Infantil')], max_length=30),
        ),
        migrations.AlterField(
            model_name='filme',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('video', models.URLField()),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodios', to='filme.filme')),
            ],
        ),
    ]
