# Generated by Django 5.2 on 2025-04-22 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0003_alter_filme_categoria_alter_filme_data_episodio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buscadecategorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='filme.filme')),
            ],
        ),
    ]
