# Generated by Django 5.2 on 2025-05-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0004_buscadecategorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='vizulizacoes',
            field=models.IntegerField(default=0),
        ),
    ]
