# Generated by Django 5.2 on 2025-05-17 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0005_filme_vizulizacoes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='vizulizacoes',
            new_name='visualizacoes',
        ),
    ]
