# Generated by Django 5.2 on 2025-05-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0006_rename_vizulizacoes_filme_visualizacoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='model',
        ),
        migrations.AddField(
            model_name='usuario',
            name='filmes_vistos',
            field=models.ManyToManyField(blank=True, related_name='usuarios_que_viram', to='filme.filme'),
        ),
    ]
